### ISSUE TITLE
error when run example [simbricks-run --verbose --force pyexps/qemu_i40e_pair.py]

### ISSUE THREAD

**Issue by huangdl123** [simbricks/simbricks#24]
root@9f1874c02330:/simbricks/experiments# simbricks-run --verbose --force pyexps/qemu_i40e_pair.py
preparing config tar: /simbricks/experiments/out/qemu-i40e-pair/1/cfg.server.0.tar
preparing config tar: /simbricks/experiments/out/qemu-i40e-pair/1/cfg.client.0.tar
preparing config tar: /simbricks/experiments/out/qemu-i40e-pair/1/cfg.client.1.tar
Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Executor.run_cmdlist() done, defined at /simbricks/experiments/simbricks/exectools.py:278> exception=RuntimeError("can't start new thread")>
Traceback (most recent call last):
  File "/simbricks/experiments/simbricks/exectools.py", line 283, in run_cmdlist
    await cmdC.start()
  File "/simbricks/experiments/simbricks/exectools.py", line 110, in start
    self.proc = await asyncio.create_subprocess_exec(*self.cmd_parts,
  File "/usr/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1667, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 212, in _make_subprocess_transport
    watcher.add_child_handler(transp.get_pid(),
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 1377, in add_child_handler
    thread.start()
  File "/usr/lib/python3.10/threading.py", line 928, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Task exception was never retrieved
future: <Task finished name='Task-5' coro=<Executor.run_cmdlist() done, defined at /simbricks/experiments/simbricks/exectools.py:278> exception=RuntimeError("can't start new thread")>
Traceback (most recent call last):
  File "/simbricks/experiments/simbricks/exectools.py", line 283, in run_cmdlist
    await cmdC.start()
  File "/simbricks/experiments/simbricks/exectools.py", line 110, in start
    self.proc = await asyncio.create_subprocess_exec(*self.cmd_parts,
  File "/usr/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1667, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 212, in _make_subprocess_transport
    watcher.add_child_handler(transp.get_pid(),
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 1377, in add_child_handler
    thread.start()
  File "/usr/lib/python3.10/threading.py", line 928, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Task exception was never retrieved
future: <Task finished name='Task-11' coro=<Executor.run_cmdlist() done, defined at /simbricks/experiments/simbricks/exectools.py:278> exception=RuntimeError("can't start new thread")>
Traceback (most recent call last):
  File "/simbricks/experiments/simbricks/exectools.py", line 283, in run_cmdlist
    await cmdC.start()
  File "/simbricks/experiments/simbricks/exectools.py", line 110, in start
    self.proc = await asyncio.create_subprocess_exec(*self.cmd_parts,
  File "/usr/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1667, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 212, in _make_subprocess_transport
    watcher.add_child_handler(transp.get_pid(),
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 1377, in add_child_handler
    thread.start()
  File "/usr/lib/python3.10/threading.py", line 928, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
qemu-i40e-pair: starting nic.client.1.
qemu-i40e-pair: starting nic.client.0.
qemu-i40e-pair: starting nic.server.0.
Task exception was never retrieved
future: <Task finished name='Task-16' coro=<ExperimentBaseRunner.start_sim() done, defined at /simbricks/experiments/simbricks/experiments.py:164> exception=RuntimeError("can't start new thread")>
Traceback (most recent call last):
  File "/simbricks/experiments/simbricks/experiments.py", line 182, in start_sim
    await sc.start()
  File "/simbricks/experiments/simbricks/exectools.py", line 110, in start
    self.proc = await asyncio.create_subprocess_exec(*self.cmd_parts,
  File "/usr/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1667, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 212, in _make_subprocess_transport
    watcher.add_child_handler(transp.get_pid(),
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 1377, in add_child_handler
    thread.start()
  File "/usr/lib/python3.10/threading.py", line 928, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Task exception was never retrieved
future: <Task finished name='Task-15' coro=<ExperimentBaseRunner.start_sim() done, defined at /simbricks/experiments/simbricks/experiments.py:164> exception=RuntimeError("can't start new thread")>
Traceback (most recent call last):
  File "/simbricks/experiments/simbricks/experiments.py", line 182, in start_sim
    await sc.start()
  File "/simbricks/experiments/simbricks/exectools.py", line 110, in start
    self.proc = await asyncio.create_subprocess_exec(*self.cmd_parts,
  File "/usr/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1667, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 212, in _make_subprocess_transport
    watcher.add_child_handler(transp.get_pid(),
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 1377, in add_child_handler
    thread.start()
  File "/usr/lib/python3.10/threading.py", line 928, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Task exception was never retrieved
future: <Task finished name='Task-17' coro=<ExperimentBaseRunner.start_sim() done, defined at /simbricks/experiments/simbricks/experiments.py:164> exception=RuntimeError("can't start new thread")>
Traceback (most recent call last):
  File "/simbricks/experiments/simbricks/experiments.py", line 182, in start_sim
    await sc.start()
  File "/simbricks/experiments/simbricks/exectools.py", line 110, in start
    self.proc = await asyncio.create_subprocess_exec(*self.cmd_parts,
  File "/usr/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1667, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 212, in _make_subprocess_transport
    watcher.add_child_handler(transp.get_pid(),
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 1377, in add_child_handler
    thread.start()
  File "/usr/lib/python3.10/threading.py", line 928, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
qemu-i40e-pair: starting net.
Task exception was never retrieved
future: <Task finished name='Task-21' coro=<ExperimentBaseRunner.start_sim() done, defined at /simbricks/experiments/simbricks/experiments.py:164> exception=RuntimeError("can't start new thread")>
Traceback (most recent call last):
  File "/simbricks/experiments/simbricks/experiments.py", line 182, in start_sim
    await sc.start()
  File "/simbricks/experiments/simbricks/exectools.py", line 110, in start
    self.proc = await asyncio.create_subprocess_exec(*self.cmd_parts,
  File "/usr/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1667, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 212, in _make_subprocess_transport
    watcher.add_child_handler(transp.get_pid(),
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 1377, in add_child_handler
    thread.start()
  File "/usr/lib/python3.10/threading.py", line 928, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
qemu-i40e-pair: starting host.client.1
qemu-i40e-pair: starting host.client.0
qemu-i40e-pair: starting host.server.0
Task exception was never retrieved
future: <Task finished name='Task-23' coro=<ExperimentBaseRunner.start_sim() done, defined at /simbricks/experiments/simbricks/experiments.py:164> exception=RuntimeError("can't start new thread")>
Traceback (most recent call last):
  File "/simbricks/experiments/simbricks/experiments.py", line 182, in start_sim
    await sc.start()
  File "/simbricks/experiments/simbricks/exectools.py", line 110, in start
    self.proc = await asyncio.create_subprocess_exec(*self.cmd_parts,
  File "/usr/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1667, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 212, in _make_subprocess_transport
    watcher.add_child_handler(transp.get_pid(),
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 1377, in add_child_handler
    thread.start()
  File "/usr/lib/python3.10/threading.py", line 928, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Task exception was never retrieved
future: <Task finished name='Task-25' coro=<ExperimentBaseRunner.start_sim() done, defined at /simbricks/experiments/simbricks/experiments.py:164> exception=RuntimeError("can't start new thread")>
Traceback (most recent call last):
  File "/simbricks/experiments/simbricks/experiments.py", line 182, in start_sim
    await sc.start()
  File "/simbricks/experiments/simbricks/exectools.py", line 110, in start
    self.proc = await asyncio.create_subprocess_exec(*self.cmd_parts,
  File "/usr/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1667, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 212, in _make_subprocess_transport
    watcher.add_child_handler(transp.get_pid(),
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 1377, in add_child_handler
    thread.start()
  File "/usr/lib/python3.10/threading.py", line 928, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Task exception was never retrieved
future: <Task finished name='Task-24' coro=<ExperimentBaseRunner.start_sim() done, defined at /simbricks/experiments/simbricks/experiments.py:164> exception=RuntimeError("can't start new thread")>
Traceback (most recent call last):
  File "/simbricks/experiments/simbricks/experiments.py", line 182, in start_sim
    await sc.start()
  File "/simbricks/experiments/simbricks/exectools.py", line 110, in start
    self.proc = await asyncio.create_subprocess_exec(*self.cmd_parts,
  File "/usr/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1667, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 212, in _make_subprocess_transport
    watcher.add_child_handler(transp.get_pid(),
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 1377, in add_child_handler
    thread.start()
  File "/usr/lib/python3.10/threading.py", line 928, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
qemu-i40e-pair: waiting for hosts to terminate
qemu-i40e-pair: cleaning up
Traceback (most recent call last):
  File "/simbricks/experiments/run.py", line 229, in <module>
    rt.start()
  File "/simbricks/experiments/simbricks/runtime/local.py", line 65, in start
    asyncio.run(self.do_run(run))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/simbricks/experiments/simbricks/runtime/local.py", line 55, in do_run
    run.output = await runner.run()
  File "/simbricks/experiments/simbricks/experiments.py", line 285, in run
    await asyncio.wait(scs)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 368, in wait
    raise ValueError('Set of coroutines/Futures is empty.')
ValueError: Set of coroutines/Futures is empty.
Future exception was never retrieved
future: <Future finished exception=CancelledError()>
Traceback (most recent call last):
  File "/simbricks/experiments/run.py", line 229, in <module>
    rt.start()
  File "/simbricks/experiments/simbricks/runtime/local.py", line 65, in start
    asyncio.run(self.do_run(run))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/simbricks/experiments/simbricks/runtime/local.py", line 55, in do_run
    run.output = await runner.run()
  File "/simbricks/experiments/simbricks/experiments.py", line 285, in run
    await asyncio.wait(scs)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 368, in wait
    raise ValueError('Set of coroutines/Futures is empty.')
ValueError: Set of coroutines/Futures is empty.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/base_subprocess.py", line 174, in _connect_pipes
    _, pipe = await loop.connect_read_pipe(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1565, in connect_read_pipe
    await waiter
asyncio.exceptions.CancelledError
Future exception was never retrieved
future: <Future finished exception=CancelledError()>
Traceback (most recent call last):
  File "/simbricks/experiments/run.py", line 229, in <module>
    rt.start()
  File "/simbricks/experiments/simbricks/runtime/local.py", line 65, in start
    asyncio.run(self.do_run(run))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/simbricks/experiments/simbricks/runtime/local.py", line 55, in do_run
    run.output = await runner.run()
  File "/simbricks/experiments/simbricks/experiments.py", line 285, in run
    await asyncio.wait(scs)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 368, in wait
    raise ValueError('Set of coroutines/Futures is empty.')
ValueError: Set of coroutines/Futures is empty.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/base_subprocess.py", line 174, in _connect_pipes
    _, pipe = await loop.connect_read_pipe(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1565, in connect_read_pipe
    await waiter
asyncio.exceptions.CancelledError
Future exception was never retrieved
future: <Future finished exception=CancelledError()>
Traceback (most recent call last):
  File "/simbricks/experiments/run.py", line 229, in <module>
    rt.start()
  File "/simbricks/experiments/simbricks/runtime/local.py", line 65, in start
    asyncio.run(self.do_run(run))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/simbricks/experiments/simbricks/runtime/local.py", line 55, in do_run
    run.output = await runner.run()
  File "/simbricks/experiments/simbricks/experiments.py", line 285, in run
    await asyncio.wait(scs)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 368, in wait
    raise ValueError('Set of coroutines/Futures is empty.')
ValueError: Set of coroutines/Futures is empty.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/base_subprocess.py", line 174, in _connect_pipes
    _, pipe = await loop.connect_read_pipe(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1565, in connect_read_pipe
    await waiter
asyncio.exceptions.CancelledError

**Comment by hajeongee** [comment]
Hi, 
It seems all the processes failed to start with this error `RuntimeError("can't start new thread")`
Could you tell more detail about your environment? And docker version are you using?

Thanks,
Hejing

**Comment by FreakyPenguin** [comment]
I'm closing this as we need more information to reproduce this. Feel free to re-open if the problem persists.
